name: Test and Deploy
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm test